### ISSUE TITLE
Honda NSX Widebody Rear Fenders

### ISSUE THREAD

**Issue by iNubby** [InZidiuZ/legacy-assets-issue-tracker#175]
Reporter: xNub#9251

Summary: In the teaser videos of the NSX, there is rear overfenders on the car, but when the car is in Los Santos Customs, there is no rear overfenders anywhere in the customizations. 

As seen in the picture, the rocket bunny rear bumper has a little piece of the overfender on it, but the main piece of the overfender isn't able to be bought anywhere. 

![image](https://user-images.githubusercontent.com/52116616/78781676-86dc7f80-7955-11ea-9c65-3c82ee0b4d26.png)

**Comment by AndersHSR** [comment]
Bumper has been fixed. The way you see it now is its final look. Make sure you are using Correct Exhaust for it :).

**Comment by iNubby** [comment]
I have the right exhaust and the right bumper and wing, but I still don't see the overfenders and the corner of the fender is still messed up with the bumper.

![image](https://user-images.githubusercontent.com/52116616/79083800-36fb1100-7ce5-11ea-8e2f-129963181b3e.png)

**Comment by AndersHSR** [comment]
The overfender should be labeled as "Right Wing", scroll through everything, if they are still missing, then it's an issue with a script, that isn't allowing to select that.

**Comment by iNubby** [comment]
Yeah, there is no option labeled "Right Wing," although there is another spoiler option but it isn't the rocket bunny spoiler.

**Comment by Karpenkooo** [comment]
Hey, 
I'm pretty sure that the "Right Wing" needs to be added to the LS Customs resource. The right-wing completely changes the look of the vehicle however you don't seem to get it in LS Customs. I recommend someone speaks to @InZidiuZ about this as he can most likely help out. 

_**Karpenko**_
